# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python\2048python\Main_Win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from BoardC import Board
import Core


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/Logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.MainWindow = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 211, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(209, 30, 81, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Score = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Score.setObjectName("Score")
        self.verticalLayout_2.addWidget(self.Score)
        self.board = Board(MainWindow)
        self.verticalLayout.addWidget(self.board)
        self.Retry_Btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Retry_Btn.setObjectName("Retry_Btn")
        self.verticalLayout_2.addWidget(self.Retry_Btn)
        self.Help_Btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Help_Btn.setObjectName("Help_Btn")
        self.verticalLayout_2.addWidget(self.Help_Btn)
        self.Close_Btn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Close_Btn.setObjectName("Close_Btn")
        self.verticalLayout_2.addWidget(self.Close_Btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Close_Btn.clicked.connect(MainWindow.close)
        self.Help_Btn.clicked.connect(MainWindow.help)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2048"))
        self.Score.setText(_translate("MainWindow", "SCORE:0"))
        self.Retry_Btn.setText(_translate("MainWindow", "Retry"))
        self.Help_Btn.setText(_translate("MainWindow", "Help"))
        self.Close_Btn.setText(_translate("MainWindow", "Close"))

import Logo_rc
